# Generated by Django 5.2.8 on 2025-11-19 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compacidade_relativa', models.FloatField(verbose_name='Compacidade Relativa')),
                ('area_superficial', models.FloatField(verbose_name='Área Superficial')),
                ('area_paredes', models.FloatField(verbose_name='Área das Paredes')),
                ('area_teto', models.FloatField(verbose_name='Área do Teto')),
                ('altura_total', models.FloatField(verbose_name='Altura Total')),
                ('orientacao', models.IntegerField(verbose_name='Orientação')),
                ('area_vidros', models.FloatField(verbose_name='Área de Vidros')),
                ('distribuicao_vidros', models.IntegerField(verbose_name='Distribuição da Área de Vidros')),
                ('carga_aquecimento', models.FloatField(verbose_name='Carga de Aquecimento')),
                ('carga_resfriamento', models.FloatField(verbose_name='Carga de Resfriamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Predição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'predicao',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
