# Generated by Django 5.2.8 on 2025-11-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logsystem',
            old_name='user',
            new_name='usuario',
        ),
    ]
