# Generated by Django 5.2.8 on 2025-11-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_logsystem_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logsystem',
            old_name='usuario',
            new_name='user',
        ),
    ]
