# Generated by Django 5.2.8 on 2025-11-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_usuario_logsystem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsystem',
            name='message',
            field=models.TextField(),
        ),
    ]
