# Generated by Django 5.2.8 on 2025-11-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_logsystem_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsystem',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logsystem',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
