# Generated by Django 5.2.8 on 2025-12-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_logsystem_action_alter_logsystem_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logsystem',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log do Sistema', 'verbose_name_plural': 'Logs do Sistema'},
        ),
        migrations.AlterField(
            model_name='logsystem',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='logsystem',
            name='message',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='logsystem',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='logsystem',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora'),
        ),
        migrations.AlterModelTable(
            name='logsystem',
            table='log_system',
        ),
    ]
